/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function ProductContainer(props) {
  const { nodes, materials } = useGLTF('/hiro-container-product.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Bottom-bottle'].geometry}
        material={materials['bottom-bottle-color']}
        position={[0.333, 0.621, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Top-bottle'].geometry}
        material={materials['top-bottle-color']}
        position={[0.248, 0.213, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
        position={[0.332, 0.76, 0]}
      />
    </group>
  )
}

useGLTF.preload('/hiro-container-product.glb')
