/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function ProductOnly(props) {
  const { nodes, materials } = useGLTF('/hiro-product.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.942, 0.768, -0.097]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials['cylinder-top-color']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials['cylinder-top-surface-top']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinderbottom.geometry}
        material={materials['cylinder-bottom-color.001']}
        position={[1.943, 0.493, -0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[1.935, 0.766, 0.073]}
        rotation={[1.573, 0, 0]}
        scale={0.087}
      />
    </group>
  )
}

useGLTF.preload('/hiro-product.glb')
